USE [master]
GO

/****** Object:  Database [JobSearch]    Script Date: 5/31/2019 3:41:05 PM ******/
DROP DATABASE [JobSearch]
GO

/****** Object:  Database [JobSearch]    Script Date: 5/31/2019 3:41:05 PM ******/
CREATE DATABASE [JobSearch]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JobSearch', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\JobSearch.mdf' , SIZE = 8192KB , MAXSIZE = 204800KB , FILEGROWTH = 20480KB )
 LOG ON 
( NAME = N'JobSearch_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\JobSearch_log.ldf' , SIZE = 8192KB , MAXSIZE = 204800KB , FILEGROWTH = 20480KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JobSearch].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [JobSearch] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [JobSearch] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [JobSearch] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [JobSearch] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [JobSearch] SET ARITHABORT OFF 
GO

ALTER DATABASE [JobSearch] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [JobSearch] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [JobSearch] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [JobSearch] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [JobSearch] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [JobSearch] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [JobSearch] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [JobSearch] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [JobSearch] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [JobSearch] SET  DISABLE_BROKER 
GO

ALTER DATABASE [JobSearch] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [JobSearch] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [JobSearch] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [JobSearch] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [JobSearch] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [JobSearch] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [JobSearch] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [JobSearch] SET RECOVERY FULL 
GO

ALTER DATABASE [JobSearch] SET  MULTI_USER 
GO

ALTER DATABASE [JobSearch] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [JobSearch] SET DB_CHAINING OFF 
GO

ALTER DATABASE [JobSearch] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [JobSearch] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [JobSearch] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [JobSearch] SET QUERY_STORE = OFF
GO

ALTER DATABASE [JobSearch] SET  READ_WRITE 
GO

